---
title: "mp4"
author: "Julia Lee, Stella Li, Irene Ryan"
date: "4/23/2018"
output:
  pdf_document: default
  html_document:
    code_folding: hide
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(RMySQL)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(mosaic)
```


```{r, message=FALSE, warning=FALSE}
db<-dbConnect_scidb(dbname = "imdb")
dbListTables(db)
```


```{r, message=FALSE, warning=FALSE}
remakesoriginals<-db %>%
dbGetQuery("SELECT t.id, t.title, t.production_year, 
  mi1.info AS votes, mi2.info AS rating, mi3.info AS Budget, 'original' AS type, mi4.info AS Languages
FROM title t 
JOIN movie_info_idx AS mi1 ON mi1.movie_id = t.id  #used  movie_id to join movie_info_idx to title
JOIN movie_link AS L on L.linked_movie_id = t.id  #used  linked_movie_id to join movie_link to title  
JOIN movie_info AS mi3 ON mi3.movie_id = t.id    #used  movie_id to join movie_info to title
JOIN movie_info AS mi4 ON mi4.movie_id = t.id    #used  movie_id to join movie_info to title
JOIN movie_info_idx AS mi2 ON mi2.movie_id = t.id #used movie_id to join movie_info_idx to title

#used index here for speed
WHERE t.kind_id = 1 #limit only to movies 
  AND mi1.info_type_id = 100 #only info aboutnumber_of_votes 
  AND mi2.info_type_id = 101  # only info about rating 
  AND mi3.info_type_id = 105  # only info about Budget
AND mi4.info = 'English' #used index limit movie to only english_language films 
AND mi1.info >25000  #only films that got more than 25000 votes
group by t.id #group by t.id(because this gives us the disnict film but it could have same title);") 


fav_stats(remakesoriginals$votes)
```


```{r, message=FALSE, warning=FALSE}
#Eliminating and movies that show up more than twice (indicating it is not an original-remake pair)
list<-remakesoriginals%>%
  group_by(title)%>%
  summarise(number=n())%>%
  filter(number==2)

#Joining with the remakesoriginals table to get the title
test<-list%>%
  inner_join(remakesoriginals, by="title")

#eliminating movies showing up in the same year (not a remake, just share the same name)
finallist<-test%>%
  group_by(title)%>%
  summarise(distinctyr=n_distinct(production_year))%>%
  filter(distinctyr==2)

#Rejoining titles, changing rating and vote variables to numeric
mp4<-finallist%>%
  inner_join(remakesoriginals, by="title")%>%
  select(-type)
mp4$votes <-as.numeric(mp4$votes)
mp4$rating <-as.numeric(mp4$rating)
```


```{r, message=FALSE, warning=FALSE}
# deleting the original movie
remakesmp4 <- mp4[c(rep(FALSE,1),TRUE), ]
# deleting the remakes
originalsmp4<-mp4[c(rep(TRUE,1), FALSE),]

# join the two df and create a new column representing the difference in vote and rating
full<-remakesmp4%>%
  left_join(originalsmp4, by="title") %>%
  mutate (diff_rating = rating.x - rating.y) %>%
  mutate (diff_votes = votes.x - votes.y) %>%
  mutate (which = ifelse(diff_rating > 0,"remake", "original" ))
#removing two leftover cases after aggregating (Crash, Legend, Passengers, The Avengers, The Gift, and Unknown)
plottingdata<-full[-c(11, 25, 30, 44, 47, 65),]
```

```{r}
#creating a remake and original column for plotting
plottingdata[["betterrated"]]=ifelse(plottingdata[["diff_rating"]] >= 0, "Remake", "Original")

#parsing budget
plottingdata[58, 14] = "$116,975.25"

parseddata <- plottingdata %>%
  mutate(parsedremake = str_extract(Budget.x, "\\$[0-9]+,[0-9]{3},[0-9]{3}|\\$[0-9]{2,3}+,[0-9]{3}"), parsedoriginal = str_extract(Budget.y, "\\$[0-9]+,[0-9]{3},[0-9]{3}|\\$[0-9]{2,3}+,[0-9]{3}"))
```


```{r}
plot2<-ggplot(data = plottingdata, aes(x= production_year.x, y = diff_rating, color= which)) + 
  geom_text(aes(label = title, size = votes.x)) 
 plot2
```



```{r}
#plot 1
ggplot(data = plottingdata, aes(x = title, y = diff_rating, fill = betterrated))+ 
  geom_col() + scale_fill_manual(values = c("Remake"="lightskyblue2", "Original"="gold1"))+
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 90, hjust = 1, size = 6), 
        panel.grid.major = element_line(color = "gray94", size = .3),
  panel.grid.minor = element_line(color = "gray94", size = .3),
  panel.background = element_rect(fill = "white",
                                color = "white"))+ 
  scale_y_continuous(breaks = c(-4, -3, -2, -1, 0, 1), labels = c("-4", "-3", "-2", "-1", "0", "1"))+ 
  guides(fill = guide_legend(title = "Better Rated"))+
    labs(x = "Movie Title", y = "Difference in Ratings", caption = "(Difference = Remake - Original)")
```



```{r}
ggplot(data=plottingdata, aes(x=title, y=diff_rating, fill=sign))+ 
  geom_col() + scale_fill_manual(values = c("positive"="lightskyblue2", negative="lightgoldenrod1"))+
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle = 90, hjust = 1))

annotate("segment", xmin = NULL, xmax = NULL,
  ymin = NULL, ymax = NULL, label = )

annotate("text", xmin = NULL, xmax = NULL,
  ymin = NULL, ymax = NULL)
```

plotting budget
```{r}
ggplot(parseddata, aes(x=parsedoriginal, y=parsedremake, fill=betterrated))+
  geom_point()

```


For our github repository, see:
<https://github.com/JuliaClaireLee/mp4.git>.





#Better Originals:

The Wicker Man review
https://www.nytimes.com/2006/09/02/movies/02wick.html

Psycho review
https://www.nytimes.com/1998/12/05/movies/film-review-psycho-the-mama-s-boy-his-motel-guest-and-that-shower.html

The Fog review
https://www.empireonline.com/movies/fog-2005/review/

Talk about how misogynist backlash affected Ghostbusters remake

#Better Remakes:

Godzilla
https://film.avclub.com/after-a-long-dry-spell-hollywood-does-godzilla-right-1798180454














